variable "name" {}
variable "description" {}
variable "ambiente" {}
variable "min_retry_interval_millis" {}
variable "control_run_state" {}
variable "tags" {}
variable "retry_on_timeout" {}
variable "max_retries" {}
variable "timeout_seconds" {}
variable "max_concurrent_runs" {}
variable "health" {}
variable "libraries" {}
variable "job_clusters" {}
variable "git_source" {}
variable "continuous" {}
variable "schedule" {}
variable "trigger" {}
variable "tasks" {}
variable "run_as" {}
variable "queue" {}
variable "notification_settings" {}
variable "email_notifications" {}
variable "webhook_notifications" {}
variable "destinatarios_alertas" {}
variable "destinatarios_alertas_streaming" {}
variable "webhook_destinations" {}
variable "parameters" {}